- name: Others
  community.general.pacman:
    state: present
    name:
      - gnome-break-timer
      - gnome-todo
      - gnome-notes
      - gnome-passwordsafe
      - gedit
      - gedit-plugins
      - catfish
      - zim
      - copyq
      - keepassxc
      - alacarte
      - android-file-transfer
