- name: USB image writer
  community.general.pacman:
    state: present
    name:
      - gnome-multi-writer
      - imagewriter
      - ventoy

- name: CLI
  community.general.pacman:
    state: present
    name:
      - nano-syntax-highlighting
      - fish
      - lsd
      - bat
      - exa
      - httpie
      - xh
      - tree
      - yay
      - git
      - fzf
      - asciinema
      - progress
      - thefuck
      - downgrade
      - htop
      - bashtop
      - btop
      - bpytop
      - tmux
      - ncdu
      - tldr

- name: Remove Gnome Terminal
  community.general.pacman:
    state: absent
    name:
      - gnome-terminal

- name: Others
  community.general.pacman:
    state: present
    name:
      - ibus-typing-booster
      - gnome-console
      - gnome-firmware
      - gnome-logs
      - gnome-usage
      - gnome-tweaks
      - dconf-editor
      # - indicator-sensors
      - plank
      - tilix
      - alacritty
      - virtualbox
      - virtualbox-guest-iso
      - font-manager
      - qt5ct
      - qt6ct
      - piper
      - psensor
      - xsensors
      - gsmartcontrol
      - nvme-cli
      - git-delta
      - duf

- name: Install system AUR packages
  become_user: "{{ current_user }}"
  kewlfft.aur.aur:
    use: yay
    extra_args: --removemake
    state: present
    name:
      - ulauncher
      - cpu-x
      # - system-monitoring-center # Project archived :(
      # - pika-backup
