- name: USB image writer
  community.general.pacman:
    state: present
    name:
      - gnome-multi-writer
      - imagewriter
      - ventoy

- name: CLI
  community.general.pacman:
    state: present
    name:
      - nano-syntax-highlighting
      - fish
      - lsd
      - bat
      - exa
      - httpie
      - xh
      - tree
      - yay
      - git
      - fzf
      - asciinema
      - progress
      - thefuck
      - downgrade
      - htop
      - bashtop
      - btop
      - bpytop
      - tmux
      - ncdu

- name: Others
  community.general.pacman:
    state: present
    name:
      - ibus-typing-booster
      - gnome-firmware
      - gnome-system-log
      - gnome-usage
      - gnome-tweaks
      - dconf-editor
      - indicator-sensors
      - plank
      - tilix
      - virtualbox
      - virtualbox-guest-iso
      - font-manager
      - qt5ct
      - cpu-x
      - piper
      - psensor
      - xsensors
      - hardinfo
      - gsmartcontrol
      - nvme-cli

- name: Install system AUR packages
  become_user: "{{ current_user }}"
  aur:
    use: yay
    extra_args: --removemake
    state: present
    name:
      - alacritty
      - ulauncher
      - git-delta-bin
      - duf-bin
      - system-monitoring-center
      - pika-backup
