- name: USB image writer
  community.general.pacman:
    state: present
    name:
      - gnome-multi-writer
      - imagewriter
      - ventoy

- name: CLI
  community.general.pacman:
    state: present
    name:
      - fish
      - lsd
      - bat
      - httpie
      - tree
      - yay
      - git
      - fzf
      - asciinema
      - progress
      - thefuck

- name: Others
  community.general.pacman:
    state: present
    name:
      - ibus-typing-booster
      - gnome-firmware
      - gnome-system-log
      - gnome-usage
      - gnome-tweaks
      - plank
      - tilix
      - cpu-x
      - psensor
      - virtualbox
      - virtualbox-guest-iso
      - hardinfo
      - font-manager

- name: Install system AUR packages
  become_user: "{{ current_user }}"
  aur:
    use: yay
    extra_args: --removemake
    state: present
    name:
      - alacritty
      - ulauncher
      - git-delta-bin
      - duf-bin
