---
- hosts: localhost
  become: yes
  vars:
    current_user: "{{ lookup('env', 'USER') }}"
  roles:
    - kewlfft.aur
    - manjaro-bloatware
    - gnome-adjust
    - games
    - office
    - internet
    - sound-and-video
    - graphics
    - utilities
    - system
    - programming
