---
- hosts: localhost
  vars:
    skip_copy: false
  roles:
    - roles/user-apps/vscode
    - role: roles/user-apps/android
      file_checksum: d71f75333d79c9c6ef5c39d3456c6c58c613de30e6a751ea0dbd433e8f8b9cbf
      file_url: https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip
      filename: android-commandlinetools-linux.zip
    - role: user-apps
      app_name: yEd
      file_checksum: 4f96611718df696de2f33eeb2cd78bfbbdacce52390afea8d00441b6fb175e20
      file_url: https://www.yworks.com/resources/yed/demo/yEd-3.23.2.zip
      filename: yed.zip
      app_folder: yed
      extracted_directory: yed-3.23.2
    - role: user-apps
      app_name: Sublime Text
      file_checksum: 8e4f70282d1081f8621c36147270e1b26809b013ce5260a4caf41e239e08249e
      file_url: https://download.sublimetext.com/sublime_text_build_4169_x64.tar.xz
      filename: sublime_text_x64.tar.bz2
      app_folder: sublime-text
      extracted_directory: sublime_text
    - role: user-apps
      app_name: Sublime Merge
      file_checksum: 4f983a807825f711b2b443ac87756e074f08adb0ef32edb8a3fd5e7421a67dde
      file_url: https://download.sublimetext.com/sublime_merge_build_2091_x64.tar.xz
      filename: sublime_merge_x64.tar.xz
      app_folder: sublime-merge
      extracted_directory: sublime_merge
    - role: user-apps
      app_name: Postman
      file_checksum: 222e927013ee631cb31f6706493b83954146de74b5ad32d31aa5ea55bcf9129a
      file_url: https://dl.pstmn.io/download/latest/linux64
      filename: postman-linux-x64.tar.gz
      app_folder: postman
      extracted_directory: Postman
    - role: user-apps
      app_name: Telegram
      file_checksum: f75239beeab815c9b1dada08e0ff84885fc85bc4919178545fffe7018ddffcc2
      file_url: https://telegram.org/dl/desktop/linux
      filename: tsetup.tar.xz
      app_folder: telegram
      extracted_directory: Telegram
    - role: user-apps
      app_name: JetBrains Intellij IDEA
      file_checksum: d252110141046388e728532c5e7a312a6d40d6b75dabb493e88c0e2b8a914574
      file_url: https://download.jetbrains.com/idea/ideaIC-2023.3.2.tar.gz
      filename: idea-ic.tar.gz
      app_folder: jetbrains-intellij-idea
      extracted_directory: idea-IC-233.13135.103
    - role: user-apps
      app_name: JetBrains PyCharm
      file_checksum: 1a4a95648c68890f2f9eb41cbb9eb041dcd08388c75a91298dfbe73f83a858c8
      file_url: https://download.jetbrains.com/python/pycharm-community-2023.3.2.tar.gz
      filename: pycharm-community.tar.gz
      app_folder: jetbrains-pycharm
      extracted_directory: pycharm-community-2023.3.2
    - role: user-apps
      app_name: Android Studio
      file_checksum: 5c5f97c871a4edd3d304729cc7ddbda9d147bba85125614edfcda68784ae583b
      file_url: https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2023.1.1.27/android-studio-2023.1.1.27-linux.tar.gz
      filename: android-studio-ide-linux.tar.gz
      app_folder: android-studio
      skip_copy: true
  tasks:
    - name: "User apps : Copy desktop entries"
      copy:
        src: desktop-entries/
        dest: ~/.local/share/applications
        directory_mode: true
    - name: "User apps : Create links for user apps on local bin directory"
      file:
        src: "~/.local/applications/{{ item.src }}"
        dest: "~/.local/bin/{{ item.dest }}"
        state: link
      with_items:
        - { src: telegram/Telegram, dest: telegram }
        - { src: android-studio/bin/studio.sh, dest: android-studio }
        - { src: jetbrains-intellij-idea/bin/idea.sh, dest: idea }
        - { src: jetbrains-pycharm/bin/pycharm.sh, dest: pycharm  }
        - { src: postman/Postman, dest: postman }
        - { src: sublime-merge/sublime_merge, dest: smerge }
        - { src: sublime-text/sublime_text, dest: subl }
        - { src: vscode/bin/code, dest: code }
    - name: "User apps : Create links for user apps on local bin directory"
      copy:
        dest: "~/.local/bin/yed"
        content: "#!/bin/bash\n\njava -jar /home/daniel/.local/applications/yed/yed.jar\n"
        mode: a+x
