---
- hosts: localhost
  tasks:
    - name: "User configs : Create workspaces directories"
      file:
        path: "~/workspaces/{{ item }}"
        state: directory
      with_items:
        - android/
        - qt/
        - others/
        - kotlin/
        - python/
        - typescript/
        - containers/
        - embedded/
        - shellscript/
    - name: "User configs : Create configuration directories"
      file:
        path: "~/{{ item }}"
        state: directory
      with_items:
        - .ssh/
        - .gnupg/
        - .config/fish/
        - .config/gtk-3.0/
        - .config/tilix/schemes/
    - name: "User configs : Copy configuration files"
      copy:
        src: "user-configs/{{ item }}"
        dest: "~/{{ item }}"
        backup: true
      with_items:
        - .gitconfig
        - .nanorc
        - .XCompose
        - .ssh/config
        - .gnupg/gpg-agent.conf
        - .config/fish/config.fish
        - .config/gtk-3.0/gtk.css
        - .config/tilix/schemes/Dracula.json
    - name: "User configs : dconf : Nautilus default sort order"
      community.general.dconf:
        key: "/org/gnome/nautilus/preferences/default-sort-order"
        value: "'type'"
        state: present
    - name: "User configs : dconf : Gnome Shell Super key"
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
      with_items:
        - { key: "/org/gnome/mutter/overlay-key", value: "'Super_R'" }
        - { key: "/org/gnome/desktop/wm/keybindings/switch-input-source", value: "['']" }
        - { key: "/org/gnome/desktop/wm/keybindings/switch-input-source-backward", value: "['']" }
        - { key: "/org/gnome/desktop/wm/preferences/mouse-button-modifier", value: "'<Alt>'" }
    - name: "User configs : dconf : System settings"
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
      with_items:
        - { key: "/org/gnome/shell/app-switcher/current-workspace-only", value: "true" } # If I use "True" ansible does not works?!
        - { key: "/org/gnome/desktop/sound/event-sounds", value: "false" }
        - { key: "/org/gnome/desktop/peripherals/touchpad/send-events", value: "'disabled-on-external-mouse'" }
    - name: "User configs : dconf : Shortcuts"
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
      with_items:
        - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-right", value: "['<Primary><Shift><Alt>Right']" }
        - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-left", value: "['<Primary><Shift><Alt>Left']" }
        - { key: "/org/gnome/desktop/wm/keybindings/close", value: "['<Alt>F4']" }
        - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-right", value: "['<Primary><Alt>Right']" }
        - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-left", value: "['<Primary><Alt>Left']" }
        - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-left", value: "['<Primary><Shift><Alt>Left']" }
        - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-left", value: "['<Primary><Shift><Alt>Left']" }
        - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-left", value: "['<Primary><Shift><Alt>Left']" }
        - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-left", value: "['<Primary><Shift><Alt>Left']" }
        - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-left", value: "['<Primary><Shift><Alt>Left']" }
        - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-left", value: "['<Primary><Shift><Alt>Left']" }
