- name: Remote control
  community.general.pacman:
    state: present
    name:
      - remmina
      - freerdp
      - libvncserver

# To use gnome sharing feature see these references:
# https://gitlab.gnome.org/GNOME/gnome-user-share/-/issues/16
# To see open ports: lsof -i -P -n
- name: Gnome settings sharing
  community.general.pacman:
    state: present
    name:
      - gnome-remote-desktop
      - gnome-user-share
      - rygel

- name: File synchronization
  community.general.pacman:
    state: present
    name:
      - grsync

- name: Others
  community.general.pacman:
    state: present
    name:
      - firefox
      - opera
      - fractal
      - fragments
      - uget
      - wireshark-qt
      - gnome-maps
      - epiphany
      - nitroshare
      - newsflash
      - geary

- name: Install internet AUR packages
  become_user: "{{ current_user }}"
  kewlfft.aur.aur:
    use: yay
    extra_args: --removemake
    state: present
    name:
      - dropbox
      - nautilus-dropbox
      - slack-desktop
      - syncthing-gtk
      - ipscan
      - junction
