- name: Others
  community.general.pacman:
    state: present
    name:
      - gnome-2048
      - gnome-mines
      - gnome-sudoku
      - gnome-games
      - lightsoff
      - snes9x-gtk
      - lutris
      - steam-manjaro
      - linuxconsole
      - evtest

- name: Install games AUR packages
  become_user: "{{ current_user }}"
  aur:
    use: yay
    extra_args: --removemake
    state: present
    name:
      - sc-controller


