- name: Others
  community.general.pacman:
    state: present
    name:
      - vym
      - minder
      - pdfarranger

- name: Install office AUR packages
  become_user: "{{ current_user }}"
  kewlfft.aur.aur:
    use: yay
    extra_args: --removemake
    state: present
    name:
      - typora
      - foxitreader
