- name: Others
  community.general.pacman:
    state: present
    name:
      - gwe
      - s-tui

- name: Install graphics AUR packages
  become_user: "{{ current_user }}"
  aur:
    use: yay
    extra_args: --removemake
    state: present
    name:
      - gst
      - gpu-viewer
      - openrgb-bin
      - mangohud

- debug:
    msg: Installing Nvidia driver...
