- name: Others
  community.general.pacman:
    state: present
    name:
      - s-tui
      - mangohud

- name: Install graphics AUR packages
  become_user: "{{ current_user }}"
  kewlfft.aur.aur:
    use: yay
    extra_args: --removemake
    state: present
    name:
      - gwe
      - gst
      - gpu-viewer
      - openrgb-bin
