- name: Others
  community.general.pacman:
    state: present
    name:
      - drawing
      - flameshot
      - gimp
      - gthumb
      - peek
      - eog
      - eog-plugins
      - curtail

- name: Install graphics AUR packages
  become_user: "{{ current_user }}"
  kewlfft.aur.aur:
    use: yay
    extra_args: --removemake
    state: present
    name:
      - gromit-mpx
      - identity
      - nomacs
