- name: Create directory to download files if it does not exist
  file:
    path: ~/Downloads/ansible/
    state: directory

- name: Create local user applications directory if it does not exist
  file:
    path: ~/.local/applications/
    state: directory

- name: Create local user bin directory if it does not exist
  file:
    path: ~/.local/bin/
    state: directory

