- name: Remove vi
  community.general.pacman:
    state: absent
    name:
      - vi
      - vim

- name: Neovim
  community.general.pacman:
    state: present
    name:
      - neovim

- name: Podman
  community.general.pacman:
    state: present
    name:
      - podman
      - podman-compose
      - podman-docker

- name: Data browsers
  community.general.pacman:
    state: present
    name:
      - sqlitebrowser

- name: Java
  community.general.pacman:
    state: present
    name:
      - jdk11-openjdk
      - jre11-openjdk
      - jre11-openjdk-headless

- name: Node.js
  community.general.pacman:
    state: present
    name:
      - nodejs-lts-fermium
      - npm

- name: Others
  community.general.pacman:
    state: present
    name:
      - moserial
      - cmake
      - gnome-builder
      - sysprof
      - gitg
      - meld
      - qtcreator

- name: Install programming AUR packages
  become_user: "{{ current_user }}"
  kewlfft.aur.aur:
    use: yay
    extra_args: --removemake
    state: present
    name:
      - lazydocker
      - valentina-studio
      - robo3t-bin
      - python-gaphor
      - commit
