- name: Others
  community.general.pacman:
    state: present
    name:
      - ciano
      - cheese
      - lollypop
      - obs-studio
      - simplescreenrecorder
      - gnome-sound-recorder
      - vlc

- name: Install sound & video AUR packages
  become_user: "{{ current_user }}"
  aur:
    use: yay
    extra_args: --removemake
    state: present
    name:
      - spotify
      - blanket-bin
