- name: Others
  community.general.pacman:
    state: present
    name:
      - ciano
      - cheese
      - lollypop
      - obs-studio
      - gnome-sound-recorder
      - vlc
      - pavucontrol
      - kooha
      - audacious
      - handbrake
      - vidcutter
      - blanket

- name: Install sound & video AUR packages
  become_user: "{{ current_user }}"
  kewlfft.aur.aur:
    use: yay
    extra_args: --removemake
    state: present
    name:
      - spotify
      - mousai
      - video-trimmer
      - simplescreenrecorder
