- name: Check if nautilus-typeahead is installed
  command: pacman -Q nautilus-typeahead
  register: pacman_check

- name: Uninstall nautilus
  community.general.pacman:
    name:
      - nautilus-admin
      - nautilus-empty-file
      - python-nautilus
      - nautilus
      - libnautilus-extension
    state: absent
  when: pacman_check.stdout.find("was not found") != -1

- name: Install nautilus-typeahead
  community.general.pacman:
    name:
      - nautilus-typeahead
      - nautilus-admin
    state: present
