- name: Check if nautilus-typeahead is installed
  command: pacman -Q nautilus-typeahead
  register: pacman_check
  ignore_errors: yes

- name: Uninstall nautilus
  community.general.pacman:
    state: absent
    name:
      - nautilus-admin
      - nautilus-empty-file
      - python-nautilus
      - nautilus
      - libnautilus-extension
  when: pacman_check.stderr.find("was not found") != -1 or pacman_check.stderr.find("não foi encontrado") != -1

- name: Install nautilus-typeahead
  community.general.pacman:
    state: present
    name:
      - nautilus-typeahead
      - nautilus-admin
